Change transaction fee => base + fast trans fee + insta fee
gelatodigital/gelato-instadapp pull request #107
Opened 2021-01-04 07:43 UTC by Gauddel

2021-01-06 12:57 UTC, gitpusha requested changes

2021-01-06 12:57 UTC, gitpusha commented on contracts/contracts/connectors/debt_bridge/from_maker/ConnectGelatoDataFullMakerToAave.sol
> +        if (_getMakerVaultCollateralBalance(vaultId) < minDebt)
should this not `_getMakerVaultDebt` instead and then be `debt < minDebt` >

2021-01-06 12:57 UTC, gitpusha commented on contracts/contracts/connectors/debt_bridge/from_maker/ConnectGelatoDataFullMakerToCompound.sol
> +        if (_getMakerVaultCollateralBalance(vaultId) < minDebt)
same here, shouldnt we check debt not collateral?

2021-01-06 12:57 UTC, gitpusha commented on contracts/contracts/connectors/debt_bridge/from_maker/ConnectGelatoDataFullMakerToMaker.sol
> +        if (_getMakerVaultCollateralBalance(vaultAId) < minDebt)
same here, shouldnt we check debt balance, not collateral balance?

2021-01-06 12:57 UTC, gitpusha commented on contracts/functions/gelato/FGelatoDebtBridge.sol
> +
I think we don't need those because they belong to the deprecated "Partial Refinancing" right?

2021-01-06 12:57 UTC, gitpusha commented on contracts/functions/gelato/FGelatoDebtBridge.sol
> +/* solhint-disable private-vars-leading-underscore, func-visibility */
I put `contracts/functions/` into `.solhintignore` - did you have linter errors nontheless?

2021-01-06 12:57 UTC, gitpusha commented on test/integration/debt_bridge/from_maker/functionality/0_ETHAToCompound.test.js
> +    const feeCollectorBalanceB = await contracts.DAI.balanceOf(feeCollector);
I think in general you should not abbreviate "Before" with "B", but write `feeCollectorBalanceBefore` otherwise it's confusing because B might be the second of A & B.

2021-01-08 15:39 UTC, Gauddel commented on test/integration/debt_bridge/from_maker/functionality/0_ETHAToCompound.test.js
> +    const feeCollectorBalanceB = await contracts.DAI.balanceOf(feeCollector);
Yes can be confusing.

2021-01-08 15:40 UTC, Gauddel commented on contracts/functions/gelato/FGelatoDebtBridge.sol
> +/* solhint-disable private-vars-leading-underscore, func-visibility */
yes i have linter error on that

2021-01-08 15:40 UTC, Gauddel commented on contracts/functions/gelato/FGelatoDebtBridge.sol
> +
ok

2021-01-08 15:42 UTC, Gauddel commented on contracts/contracts/connectors/debt_bridge/from_maker/ConnectGelatoDataFullMakerToAave.sol
> +        if (_getMakerVaultCollateralBalance(vaultId) < minDebt)
yes we should compare debt.

2021-01-10 16:24 UTC, closed without merging