refactored debt & colla passing
gelatodigital/gelato-instadapp pull request #113
Opened 2021-01-13 19:54 UTC by hilmarx

2021-01-13 19:59 UTC, hilmarx commented on test/gas/debt_bridge/full/from_maker/helpers/services/getSpellsETHAToAave.mock.js
> +      ],
are these the correct inputs @Gauddel, for example, can we pass the debt denominated in DAI or does it have to be denominated in ETH?

2021-01-14 11:45 UTC, gitpusha requested changes

2021-01-14 11:45 UTC, gitpusha commented on contracts/contracts/connectors/debt_bridge/from_maker/ConnectGelatoDataMakerToAave.sol
> -                _getMakerVaultCollateralBalance(_vaultId),
@hilmarx I think the problem with your suggested changes is that they render the the individual connectors e.g. `ConnectGelatoDataMakerToAave` useless on their own because you assume that they are always passed the `debtAmt` and `colAmt` in real time by something else. 

You strip them of their ability to dynamically get these values themselves. 

I guess we could do something like: 

```solidity
uint256 daiToBorrow = _daiToBorrow == 0 ? _getRealisedDebt(_getMakerVaultDebt(_vaultAId)) : _daiToBorrow;
```

in there instead to have the best of both worlds. Same for colToWithdraw .

2021-01-14 11:45 UTC, gitpusha commented on contracts/interfaces/InstaDapp/connectors/IConnectGelatoDataMakerToAave.sol
> +        uint256 _colAmt
Don't commit this just to visualize: 

```suggestion
        uint256 _vaultId,
        address _colToken,
        uint256 _colAmt,
        uint256 _debtAmt
```

Better to stick to one ordering of parameters everywhere. first `collateral` related params. Then `debt` .

2021-01-14 11:45 UTC, gitpusha commented on test/integration/debt_bridge/from_maker/helpers/services/getSpellsETHAToETHB.js
> +        constants.MAKER_INITIAL_ETH,
Let's stick to one parameter ordering everywhere: 

1. collateral stuff
2. debt stuff

2021-01-14 14:16 UTC, gitpusha commented
closing as would have to be refactored to be viable and @Gauddel does not think the optimization is worth the change and added new complexity. I agree with him because even if we go for my suggestion

`uint256 debtAmt = _debtAmt == 0 ? _getRealisedDebt(_getMakerVaultDebt(_vaultAId)) : _debtAmt;`

changing the function APIs to take two new parameters ( `_colAmt` , `_debtAmt` ) is ugly because it requires a lot of documentation to make sure no human error is madde. These parameters are not meant for human input. They are only for smart contracts. Too easy to make a mistake here. 

Since we will probably change a lot for GelatoV2 anyway we can live without the little gas optimization we would get from cutting these 2 extra state reads.

2021-01-14 14:16 UTC, closed without merging