Use Oracle Aggregator and refacto
gelatodigital/gelato-instadapp pull request #129
Opened 2021-01-22 08:12 UTC by Gauddel

2021-01-22 17:27 UTC, gitpusha requested changes

2021-01-22 17:27 UTC, gitpusha commented on contracts/contracts/gelato/conditions/aave/ConditionMakerToAaveSafe.sol
>      uint256 public immutable fees;
these are the InstaDapp fees 

We currently set them to 0.3% but this might change - ideally we store `ConnectGelatoDataMakerToAave` here instead and read the `fees` from the connector dynamically at execution time. Same for all other conditions that make use of the hardcoded fees.

2021-01-22 17:34 UTC, gitpusha submitted a review, later dismissed

2021-01-22 17:34 UTC, gitpusha commented on hardhat.config.js
> +  "0x7354C81fbCb229187480c4f497F945C6A312d5C3":
I wouldnt clutter the hardhat.config.js file with this - better to import it.

2021-01-22 17:42 UTC, Gauddel commented on contracts/contracts/gelato/conditions/aave/ConditionMakerToAaveSafe.sol
>      uint256 public immutable fees;
sure, initially it was immutable. We can now choose to read from the connector.

2021-01-22 17:44 UTC, Gauddel commented on hardhat.config.js
> +  "0x7354C81fbCb229187480c4f497F945C6A312d5C3":
Once the oracle aggregator will be deployed we won't need this information anymore

2021-01-23 13:38 UTC, hilmarx commented on contracts/vendor/Convert.sol
>      amt = _mul(_amt, 10**(18 - _dec));
dont know if I am stupid, but where exactly is this `_mul` func?

2021-01-23 13:39 UTC, hilmarx commented on contracts/vendor/Convert.sol
>  function _convertTo18(uint256 _dec, uint256 _amt) pure returns (uint256 amt) {
what happens if '_amt' is 18, does this return 0?

2021-01-23 13:44 UTC, hilmarx commented on contracts/contracts/connectors/debt_bridge/from_maker/ConnectGelatoDataMakerToAave.sol
> +        gasFeesPaidFromDebt = _convertTo18(decimals, gasFeesPaidFromDebt);
why convert again to 10 decimals?

2021-01-23 13:57 UTC, hilmarx commented on contracts/contracts/gelato/conditions/aave/ConditionMakerToAaveSafe.sol
>      uint256 public immutable fees;
Resolved in #134

2021-01-25 10:32 UTC, hilmarx commented on contracts/vendor/Convert.sol
>  function _convertTo18(uint256 _dec, uint256 _amt) pure returns (uint256 amt) {
it returns 1 right?

2021-01-25 10:36 UTC, Gauddel commented on contracts/vendor/Convert.sol
>  function _convertTo18(uint256 _dec, uint256 _amt) pure returns (uint256 amt) {
yes

2021-01-25 10:37 UTC, Gauddel commented on contracts/vendor/Convert.sol
>      amt = _mul(_amt, 10**(18 - _dec));
come from mul of DSMath.

2021-01-25 11:07 UTC, hilmarx approved these changes

2021-01-25 11:08 UTC, merged