wip:feat:Debt Bridge v1
gelatodigital/gelato-instadapp pull request #17
Opened 2020-10-08 10:52 UTC by Gauddel

2020-10-08 13:54 UTC, gitpusha commented on buidler.config.js
> +  bre.constants = constants;
Just so you know, from now on we will stop putting global variables into the environment. In every file we will be explicit about the variables we define and import. Typescript will later on force us to be explicit anyway.

2020-10-08 13:55 UTC, gitpusha commented on buidler.config.js
> +      timeout: 120000,
Just so you know, timeout is also a  Standard Config field for every network.

2020-10-08 13:56 UTC, gitpusha commented on contracts/CompoundBorrowRate.sol
> +    using SafeMath for uint;
We should be explicit in Solidity everywhere. We should use `uint256` instead of `uint` short form.

2020-10-08 16:09 UTC, gitpusha requested changes

2020-10-08 16:09 UTC, gitpusha commented on test/3_Debt-Bridge-External-Provider.test.js
> +      conditions: [conditionCompareRate.address],
I think we are missing Conditions to make sure that the DSA still has the Vault open - we don't need to make a check whether the DSA has any DAI balance to paybackMaker because we use the flashloan anyway.

2020-10-08 16:09 UTC, gitpusha commented on test/3_Debt-Bridge-External-Provider.test.js
> +    const spellsActionsFramework = [];
I don't like the "framework" name. Let's just call it "spells" and use the same naming InstaDapp uses.

2020-10-08 16:09 UTC, gitpusha commented on test/3_Debt-Bridge-External-Provider.test.js
> +    ).to.be.equal(gasPriceCeil);
You can also combine this with multiProvide instead

2020-10-08 16:09 UTC, gitpusha commented on test/3_Debt-Bridge-External-Provider.test.js
> +      )
You can also combine this into the `multiProvide` instead

2020-10-08 16:09 UTC, gitpusha commented on test/3_Debt-Bridge-External-Provider.test.js
> +    const gasPriceCeil = constants.MaxUint256;
You can put all of this together with the `Task` creation and just reuse the Actions for both TaskSpec whitelisting and Task instantiation.

2020-10-08 16:09 UTC, gitpusha commented on test/3_Debt-Bridge-External-Provider.test.js
> +    spells.push(flashPayBack);
Reuse the Actions first to multiProve TaskSpecs - we can cut and reuse a lot of code here. Because a `TaskSpec` is made of the same `Action` type a `Task` is made of. Gelato handles cutting the `data` from `Action` during `TaskSpec` whitelisting, see: https://github.com/gelatodigital/gelato-network/blob/0941d7911aaca9f7ab36064e4dba9418ea1ca7ed/contracts/gelato_core/GelatoProviders.sol#L334

2020-10-08 16:09 UTC, gitpusha commented on test/3_Debt-Bridge-External-Provider.test.js
> +
Later when we pay the Provider , we should make sure to also include a test to verify that the Provider received Tokens.

2020-10-09 07:58 UTC, Gauddel commented on contracts/CompoundBorrowRate.sol
> +        return cToken.borrowRatePerBlock().mul(2102400).mul(1e9); // Get ray version of the annual rate.
This is the number of block per year of compound protocol. You can find it as a property named  _blocksPerYear_ in this contract [JumpInterestModel.sol](https://github.com/compound-finance/compound-protocol/blob/master/contracts/JumpRateModel.sol). But this property isn't present in each rate model contract, so i put it directly in CompoundBorrowRate.sol.

2020-10-19 06:28 UTC, closed without merging

2020-10-19 12:47 UTC, gitpusha reviewed
PR closed